# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch 

# Create random tensor
torch.rand(size=(7,7))

tensor([[0.4461, 0.0035, 0.6652, 0.5985, 0.6961, 0.3326, 0.7431],
        [0.3991, 0.9875, 0.3059, 0.1368, 0.7918, 0.7941, 0.4970],
        [0.1257, 0.3650, 0.1415, 0.7110, 0.2714, 0.9298, 0.0016],
        [0.2560, 0.9281, 0.6120, 0.1774, 0.5941, 0.9465, 0.0708],
        [0.4458, 0.3786, 0.9780, 0.3363, 0.5536, 0.7808, 0.7103],
        [0.4659, 0.6693, 0.2997, 0.7912, 0.9368, 0.4701, 0.9739],
        [0.7871, 0.8025, 0.9701, 0.3380, 0.5739, 0.2610, 0.0676]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [39]:
# Create another random tensor
torch.manual_seed(1234)
# Perform matrix multiplication 
a=torch.rand(size=(1,7)).T
b=torch.tensor([2.0])
print(a.shape,b.shape)
print(torch.matmul(a,b))



torch.Size([7, 1]) torch.Size([1])
tensor([0.0580, 0.8038, 0.5197, 0.7333, 0.1166, 1.4013, 0.1036])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [40]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
a = torch.rand(size=(3,4))
b= torch.rand(size=(5,3))

# Matrix multiply tensors
torch.matmul(b,a)

tensor([[0.1969, 0.3100, 0.1873, 0.2724],
        [0.8363, 1.3466, 0.6669, 1.0153],
        [0.4772, 0.7337, 0.3904, 0.5481],
        [0.9745, 1.5076, 0.5806, 0.8280],
        [0.8122, 1.2752, 0.6405, 0.9338]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [43]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [50]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())

# Create two random tensors on GPU
a = torch.rand(size=(2,3)).to('cuda')
b= torch.rand(size=(2,3)).to('cuda')

print(a)
print(b)

True
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [49]:
a.device.type, b.device.type

('cuda', 'cuda')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [54]:
# Perform matmul on tensor_A and tensor_B
C=torch.matmul(a,b.T)
C, C.size()


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [55]:
# Find max
print(C.max())
# Find min
print(C.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [56]:
# Find arg max
print(C.argmax())

# Find arg min
print(C.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [59]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a=torch.rand(size=(1,1,1,10))
print(a, a.size())
# Remove single dimensions
b=a.squeeze()
print(b)

# Print out tensors and their shapes
print(b.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
